name: Push Main CI

on:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    name: build&test
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: uses Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - run: yarn --frozen-lockfile

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3
